# azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: test
    value: '012_azure_pipelines/http_get.js'

parameters:
  - name: options
    values:
      - stressOptions
      - smokeOptions
steps:
  - pwsh: |
      ls
  - task: k6-load-test@0
    inputs:
      filename: $(test)
      args: -e options=${{ parameters.options }}